version: "3.7"

services:
  database:
    image: postgres
    container_name: database_ecommerceApp
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=ecommerceApp
    volumes:
      - pgdata:/data/postgres


  redis:
    image: redis:alpine
    container_name: redis_cobaia
    ports:
      - 6379:6379

  app:
    build: .
    container_name: ecommerceApp
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database
      - redis



volumes:
  pgdata:
    driver: local
    